version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./web/static:/home/app/microservice/static
    depends_on:
      - web
    restart: "always"
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/cakestore
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
