# Generated by Django 3.0.3 on 2020-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("webstore", "0002_auto_20200831_1529")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, max_length=40),
        )
    ]
