# Generated by Django 3.0.3 on 2020-08-31 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("webstore", "0005_auto_20200831_1535")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="categories"
            ),
            preserve_default=False,
        )
    ]
