# Generated by Django 3.0.3 on 2020-08-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("webstore", "0003_auto_20200831_1530")]

    operations = [migrations.RemoveField(model_name="category", name="slug")]
